name: CI/CD Tienda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependencias (Strapi)
        run: |
          cd backend
          pnpm install

      - name: Construir proyecto (Strapi)
        run: |
          cd backend
          pnpm run build

      - name: Instalar dependencias (Next.js)
        run: |
          cd web
          pnpm install

      - name: Construir proyecto (Next.js)
        run: |
          cd web
          pnpm run build
        env:
          STRAPI_HOST: "https://mi-tienda-backend-y9xx.onrender.com"
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}

      - name: Verificar archivos generados
        run: |
          echo "Contenido de web:"
          ls -la web
          echo "Contenido de web/.next:"
          ls -la web/.next || true
          echo "Contenido de web/.next:"
          find web/.next -maxdepth 2 -type f | head -30 || true

      - name: Subir Artefacto de compilación de Next.js
        uses: actions/upload-artifact@v4
        with:
          name: web-compilado
          path: web/.next
          retention-days: 5